### ISSUE TITLE
'release' workflow: patched changelog contains CRLF instead of LF, does not have newline at end of file

### ISSUE THREAD

**Issue by KENNYSOFT** [JetBrains/gradle-changelog-plugin#104]
**Describe the bug:**

In the 'release' workflow, the patched changelog contains CRLF instead of LF and does not have newline at end of file. I think the Gradle task 'patchChangelog' does it.

![image](https://user-images.githubusercontent.com/6624567/154811872-b0560134-7cec-49f8-ad1f-ca557766f961.png)

Reference: KENNYSOFT/IDEA-260828-Korean#2

Also, I've made the .gitattributes file to ensure the correct line ending (KENNYSOFT/IDEA-260828-Korean@b88aa75cfc3b05afd6ad1c16c03ceb5a4c67f79f) but it seems that it's not applied well.

**Steps to reproduce:** 

1. Write a changelog in the file, and commit it with LF.
1. Release a new version.
1. Auto-generated PR contains a change to CRLF.

**Expected behavior:**

Patch the file with LF, or at least apply the .gitattributes file.

**Additional context:**

To see the newline character difference, use `--ws-error-highlight=all` option to the Git command. (e.g., `git diff`, `git show`)

**Comment by hsz** [comment]
A new line at the end is already resolved with #126

**Comment by JojOatXGME** [comment]
I also noticed the CRLF in the `CHANGELOG.md` some time ago. The problem still exists in version 2.1.0. The CRLF is not introduced by this plugin, but by GitHub. It looks like the release notes retrieved from GitHub always uses CRLF. The [intellij-platform-plugin-template](https://github.com/JetBrains/intellij-platform-plugin-template/blob/afe711755bbbccb402c5463787347c09b16493d0/.github/workflows/release.yml#L55) uses `patchChangelog --release-note=` to replace part of the file with the release notes from GitHub. For [nix-idea](https://github.com/NixOS/nix-idea/blob/59cc3e911fb468b225a92c1e331d135ec56e01cf/gradle/bumpVersion.gradle.kts#L19-L26), I used the following workaround:

```kotlin
tasks.named("patchChangelog") {
    // GitHub seems to use CRLF as line feeds.
    // We have to replace them to avoid files with mixed line endings.
    doFirst {
        val releaseNote = property("releaseNote")
        if (releaseNote is String) {
            setProperty("releaseNote", releaseNote.replace("\r\n", "\n"))
        }
    }
}
```
